### PR TITLE
Performance Improvement on Dense Shapes 

### PR DESCRIPTION
**Pull request by jomach**
Performance Improve on Dense Shapes or when Index returns a lot of candidates.

On my Use cases I get like 200M rows and I have 20000 shapes. 
The NearestD takes forever because the query on the STRtree returns the hole 20 000

With this if the user starts with a small radius let's say 0.0001 if the index does not returning anything then we expand the point and try the query again.

### CODE REVIEW

**Comment by syoummer** [comment]
I have changed to nearest neighbor search provided by JTS. 

http://tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/index/strtree/STRtree.html

**Comment by jomach** [comment]
Hi, 
This is nice, but one question why do you expand the geometry again on BroadcastSpatialJoin line 57: 

> queryEnv.expandBy(radius) ? 

You already do that on line 76. Can you explain ? thanks

PS: I try your code and it does not work I get : 

> org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 4.0 failed 1 times, most recent failure: Lost task 1.0 in stage 4.0 (TID 9, localhost): java.lang.ClassCastException: scala.Tuple2 cannot be cast to com.vividsolutions.jts.geom.Geometry

Do you have a test for this ?

**Comment by syoummer** [comment]
Thanks for pointing out the error. Those are several mistake I have made in the code. Now it works properly. 

BTW, I am thinking about using your search implementation as a basis of KNN search.

**Comment by jomach** [comment]
Hi Syoummer, 
How does the nearest nearestNeighbour knows if we have two diferent shapes but with the same envelop ? We actually should return an array of lets say 5 nearestNeighbour and then calculate the distance from the original object. You know what I mean ?

**Comment by syoummer** [comment]
From what I read from the documentation, JTS will first use envelop to find nearest candidates and then calculate the distance from geometries (using the `ItemDistance` parameter) as you mentioned.

**Comment by jomach** [comment]
@syoummer : Can you share the link on this ?

**Comment by syoummer** [comment]
[link](http://tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/index/strtree/STRtree.html#nearestNeighbour%28com.vividsolutions.jts.geom.Envelope, java.lang.Object, com.vividsolutions.jts.index.strtree.ItemDistance%29)

**Comment by syoummer** [comment]
BTW, I have extend the `ItemDistance` class in the code to do the real geometry distance.

**Comment by jomach** [comment]
I saw that, it improves performance more then 400% :)  from 40 min I get to 5 min. 
My only question was : if the calculation is happening on the bbox. On the docs I read: 

> Finds the two nearest items in the tree, using ItemDistance as the distance metric. A Branch-and-Bound tree traversal algorithm is used to provide an efficient search

So the class that you extended will be call multiple times with possible candidates and calculate the distance is that it ? And the candidates for that are getted as "querying" the index but this happens internally right ?

**Comment by syoummer** [comment]
I didn't look into their code, but it supposes to work correctly. Since I already have my own R-tree, in the future I am thinking about having an independent implementation rather than calling the JTS (I hope it will be more efficient).

**Comment by jomach** [comment]
So I checked the code and we are fine with this implementation. 
`while(!priQ.isEmpty() && distanceLowerBound > 0.0D) {
            BoundablePair bndPair = (BoundablePair)priQ.poll();
            double currentDistance = bndPair.getDistance();
            if(currentDistance >= distanceLowerBound) {
                break;
            }
            if(bndPair.isLeaves()) {
                distanceLowerBound = currentDistance;
                minPair = bndPair;
            } else {
                bndPair.expandToQueue(priQ, distanceLowerBound);
            }
        }`

the method getDistance if the we provide a geometry and they are leaves then we calculate on the shapes if not they calculate on the Envelope. I will close this. But nice to talk with you. Regards
Jorge

F\* this mark up...

**Comment by syoummer** [comment]
Great!

**Pull request closed without merging**
